package ssm.mapper.mineMapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import ssm.pojo.Mine.Customer;
import ssm.pojo.Mine.CustomerExample;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Mar 28 10:49:02 CST 2019
     */
    int countByExample(CustomerExample example);
    Customer selectByUsernameAndPassword(Customer customer);
    List<Customer> selectFollowDetail(String u_id);
    void updateCustomer(Customer customer);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Mar 28 10:49:02 CST 2019
     */
    int deleteByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Mar 28 10:49:02 CST 2019
     */
    int deleteByPrimaryKey(String uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Mar 28 10:49:02 CST 2019
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Mar 28 10:49:02 CST 2019
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Mar 28 10:49:02 CST 2019
     */
    List<Customer> selectByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Mar 28 10:49:02 CST 2019
     */
    Customer selectByPrimaryKey(String uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Mar 28 10:49:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Mar 28 10:49:02 CST 2019
     */
    int updateByExample(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Mar 28 10:49:02 CST 2019
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Mar 28 10:49:02 CST 2019
     */
    int updateByPrimaryKey(Customer record);
	int findDynamicCount(String u_id);
	int findfollowCount(String u_id);
	int findfanCount(String u_id);
	List<Customer> selectFanDetail(String u_id);
	//后台管理
	List<Customer> selectallCustomer();

	Customer selectByU_id(String u_id);

	void editCustomer(Customer customer);

	void deleteCustomer(String u_id);

	void addCustomer(Customer customer);
	
	List<Customer> SelectHighRisk();
	
	public void updataCustomerCancellationCount(Customer customer);
	
	public Customer findCustomerById(String u_id);
	
	/**
	 * 修改个人密码
	 * @param customer
	 */
	public void updateCustomerPwd(Customer customer);
	
	/**
	 * 修改个人信息
	 * @param customer
	 */
	public void updateCustomerInfo(Customer customer);
}